name: build

on:
  push:
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["windows"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Install dependencies
        run: shards install --without-development --release

      - name: Build Windows Binaries
        if: matrix.os == 'windows'
        run: |
          crystal build lock.cr --release -o bin/lock.exe
          crystal build shock.cr --release -o bin/shock.exe
          crystal build barrel.cr --release -o bin/barrel.exe
          crystal build trick.cr --release -o bin/trick.exe
          
          Compress-Archive -Path bin/* -DestinationPath bin/CrystalTools-windows.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v') # Vérifie si c'est un tag
        with:
          files: bin/CrystalTools-windows.zip
